repos:
-   repo: local
    hooks:
    -   id: clean_csvs
        name: clean_csvs
        entry: scripts/clean_csvs.py
        language: script
        types: [python]
        always_run: true
    -   id: validate_references
        name: validate_references
        entry: scripts/validate_references.py
        language: script
        types: [python]
        always_run: true
